### ISSUE TITLE
[FR] Add option to expose /lower as a bind mount for direct access

### ISSUE THREAD

**Issue by henryptung** [RPi-Distro/raspi-config#176] opened 2022-01-05 22:29 UTC
Exposing `/lower` can allow for easier targeted maintenance in certain cases, e.g. tweaking configs.

**Comment by XECDesign** [comment] 2022-01-06 07:33
Duplicate of #100. Sounds good, but it's fairly low on the todo list.

**Closed by XECDesign** 2022-01-06 07:33 UTC
